# Generated by Django 5.1.6 on 2025-04-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDropout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('caste', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('standard', models.CharField(max_length=10)),
                ('dropout_year', models.PositiveIntegerField()),
            ],
        ),
    ]
